import type { PersonalArchivePort } from '../archive/sandbox-native.js';
import type { IntakeService } from '../services/intake-service.js';
import { mkdtempSync, mkdirSync, openSync, closeSync, constants, fsyncSync, writeFileSync, rmdirSync } from 'node:fs';
import { join } from 'node:path';
import { z } from 'zod';
import { ensurePrivateDirectory } from '../db/permissions.js';
import { attachmentArchiveRequestSchema, type Attachment, type AttachmentArchiveRequest, type AttachmentArchiveResult } from '../../shared/api/attachments.js';
import { intakeFieldsSchema, type IntakePreviewRequest } from '../../shared/api/intake.js';
import { PublicApiError } from '../../shared/api/errors.js';
import { inferIntakeFields, planIntakeMain } from '../archive/intake-plan.js';
import { parseArchiveIntent } from '../archive/archive-snapshot.js';
import { sha256Bytes } from '../vault/raw-bytes.js';
import type { StoredAttachment } from './service.js';

export type AttachmentArchivePort = { port: PersonalArchivePort; intakeService: IntakeService };
type IntakeFields = z.infer<typeof intakeFieldsSchema>;
type Text = { parser: string; pages: { page: number; text: string }[]; textRevision: string };
const planSchema = z.object({ fields: intakeFieldsSchema, intakeName: z.uuid(), mainName: z.string(), target: z.string(), mainSha: z.string(), published: z.boolean() });

/** Read-only data safe to pass to the action-plan service. Generated bytes stay private. */
export type AttachmentArchivePreview = {
  attachmentId: string;
  attachmentSha256: string;
  attachmentName: string;
  archiveFields: IntakeFields;
  textRevision: string;
  target: string;
  mainName: string;
  mainSha256: string;
  duplicate: boolean;
  existing?: AttachmentArchiveResult;
};

type BuiltPreview = AttachmentArchivePreview & {
  item: StoredAttachment;
  attachment: Attachment;
  original: Buffer;
  originalName: string;
  staged: ReturnType<typeof planIntakeMain>;
  plan: z.infer<typeof planSchema>;
  duplicateRecord?: StoredAttachment;
};

function fail(code: string, message: string): never { throw new PublicApiError(code, message, 409); }

export function createAttachmentArchive(input: {
  stagingDirectory: string;
  port?: AttachmentArchivePort;
  record(id: string): StoredAttachment;
  persist(record: StoredAttachment): void;
  list(): StoredAttachment[];
  readOriginal(id: string): { attachment: Attachment; bytes: Buffer };
  parsed(id: string): Text;
  now(): Date;
}) {
  let running: { id: string; done: Promise<AttachmentArchiveResult> } | undefined;

  function storedResult(item: Attachment, duplicate: boolean, resultId = item.id): AttachmentArchiveResult {
    const value = item.archive;
    if (!value?.operationId || !value.materialPath || !value.target) fail('ATTACHMENT_ARCHIVE_INCOMPLETE', '归档回执不完整，请继续核验。');
    return { id: resultId, state: value.state === 'archived' ? 'archived' : 'needs-review', operationId: value.operationId, materialPath: value.materialPath, target: value.target, indexed: value.indexed ?? false, duplicate };
  }

  function exists(port: PersonalArchivePort, path: string): boolean {
    try { return port.stat(path) !== null; }
    catch (error) { if (error instanceof Error && error.message === 'NOT_FOUND') return false; throw error; }
  }

  function originalName(attachment: Attachment): string {
    return `原件.${attachment.mediaType === 'application/pdf' ? 'pdf' : attachment.mediaType === 'text/markdown' ? 'md' : 'txt'}`;
  }

  function verifyArchivedOriginal(port: PersonalArchivePort, attachment: Attachment, problemCode = 'ATTACHMENT_ARCHIVE_ORIGINAL_CHANGED'): void {
    const archive = attachment.archive;
    const name = originalName(attachment);
    try {
      if (!archive?.target || sha256Bytes(port.read(`${archive.target}/附件/${name}`)) !== attachment.sha256) throw Error('changed');
    } catch { fail(problemCode, problemCode === 'ATTACHMENT_ARCHIVE_COMMITTED_ORIGINAL_CHANGED'
      ? '归档已取得操作回执，但原件校验未完成；恢复记录已保留，请继续核验。'
      : '已归档原件缺失或已变化，请先恢复或核对原件；未重复创建。'); }
  }

  function publish(staged: ReturnType<typeof planIntakeMain>, id: string, originalFileName: string, original: Buffer, port: PersonalArchivePort): void {
    if (!port.publishAttachmentPackage) fail('ATTACHMENT_ARCHIVE_UNAVAILABLE', '请更新桌面归档模块后重试，原件仍保留。');
    ensurePrivateDirectory(input.stagingDirectory);
    const attempt = mkdtempSync(join(input.stagingDirectory, 'attempt-'));
    const folder = join(attempt, id);
    mkdirSync(folder, { mode: 0o700 });
    mkdirSync(join(folder, '附件'), { mode: 0o700 });
    for (const [path, bytes] of [[join(folder, staged.mainName), staged.bytes], [join(folder, '附件', originalFileName), original]] as const) {
      const fd = openSync(path, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600);
      try { writeFileSync(fd, bytes); fsyncSync(fd); } finally { closeSync(fd); }
    }
    port.publishAttachmentPackage(attempt, id, staged.mainName, staged.bytes, originalFileName, original);
    try { rmdirSync(attempt); } catch { /* Keep unexpected contents for inspection. */ }
  }

  /**
   * Build all deterministic archive data without persisting a ledger, publishing a
   * package, or opening an IntakeService transaction. The generated bytes remain
   * in this module so callers only receive hashes and paths.
   */
  async function buildPreview(request: AttachmentArchiveRequest, signal?: AbortSignal): Promise<BuiltPreview> {
    signal?.throwIfAborted();
    const parsedRequest = attachmentArchiveRequestSchema.parse(request);
    if (!input.port) fail('ATTACHMENT_ARCHIVE_UNAVAILABLE', '当前连接不能归档附件；原件已保留。');
    const { port } = input.port;
    const item = input.record(parsedRequest.id);
    const original = input.readOriginal(parsedRequest.id);
    const attachment = original.attachment;
    const date = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Shanghai', year: 'numeric', month: '2-digit', day: '2-digit' }).format(input.now());

    if (attachment.archive?.state === 'archived') {
      const archived = attachment.archive;
      if (!archived.materialPath || !archived.target || !exists(port, archived.materialPath)) fail('ATTACHMENT_ARCHIVE_MISSING', '曾归档的资料已移走或回收；请先恢复，未重复创建。');
      verifyArchivedOriginal(port, attachment);
      const archivedPlan = item.archivePlan ? planSchema.safeParse(item.archivePlan) : undefined;
      const fields = archivedPlan?.success ? archivedPlan.data.fields : intakeFieldsSchema.parse({ platform: '个人', title: attachment.name.replace(/\.(pdf|md|txt)$/iu, ''), collectedAt: date });
      return {
        attachmentId: attachment.id, attachmentSha256: attachment.sha256, attachmentName: attachment.name,
        archiveFields: fields, textRevision: '', target: archived.target, mainName: archivedPlan?.success ? archivedPlan.data.mainName : '原文.md',
        mainSha256: archivedPlan?.success ? archivedPlan.data.mainSha : attachment.sha256, duplicate: true,
        existing: storedResult(attachment, true), item, attachment, original: original.bytes, originalName: originalName(attachment),
        staged: { platform: fields.platform, month: fields.collectedAt.slice(0, 7), packageName: parsedRequest.id, mainName: archivedPlan?.success ? archivedPlan.data.mainName : '原文.md', bytes: Buffer.alloc(0), sourceMainName: attachment.name },
        plan: archivedPlan?.success ? archivedPlan.data : { fields, intakeName: parsedRequest.id, mainName: '原文.md', target: archived.target, mainSha: attachment.sha256, published: true }
      };
    }

    const candidateDuplicate = input.list().find(other => other.attachment.id !== parsedRequest.id && other.attachment.sha256 === attachment.sha256 && other.attachment.archive?.state === 'archived');
    const candidateArchive = candidateDuplicate?.attachment.archive;
    const duplicateRecord = candidateDuplicate && candidateArchive?.materialPath && candidateArchive.target && exists(port, candidateArchive.materialPath)
      ? candidateDuplicate
      : undefined;
    if (duplicateRecord) {
      const duplicateArchive = duplicateRecord.attachment.archive!;
      verifyArchivedOriginal(port, duplicateRecord.attachment);
      const duplicatePlan = duplicateRecord.archivePlan ? planSchema.safeParse(duplicateRecord.archivePlan) : undefined;
      const duplicateFields = duplicatePlan?.success
        ? duplicatePlan.data.fields
        : intakeFieldsSchema.parse({ platform: '个人', title: attachment.name.replace(/\.(pdf|md|txt)$/iu, ''), collectedAt: date });
      const duplicateMaterialPath = duplicateArchive.materialPath!;
      const duplicateMainName = duplicatePlan?.success
        ? duplicatePlan.data.mainName
        : duplicateMaterialPath.slice(duplicateArchive.target!.length + 1);
      const duplicateMainSha = duplicatePlan?.success
        ? duplicatePlan.data.mainSha
        : sha256Bytes(port.read(`${duplicateArchive.target}/${duplicateMainName}`));
      const duplicateTextRevision = ['ready', 'needs-ocr'].includes(attachment.status)
        ? input.parsed(parsedRequest.id).textRevision
        : '';
      return {
        attachmentId: attachment.id, attachmentSha256: attachment.sha256, attachmentName: attachment.name,
        archiveFields: duplicateFields, textRevision: duplicateTextRevision, target: duplicateArchive.target!,
        mainName: duplicateMainName, mainSha256: duplicateMainSha, duplicate: true,
        existing: storedResult(duplicateRecord.attachment, true, attachment.id), item, attachment, original: original.bytes,
        originalName: originalName(attachment), duplicateRecord,
        staged: { platform: duplicateFields.platform, month: duplicateFields.collectedAt.slice(0, 7), packageName: parsedRequest.id, mainName: duplicateMainName, bytes: Buffer.alloc(0), sourceMainName: attachment.name },
        plan: duplicatePlan?.success ? duplicatePlan.data : { fields: duplicateFields, intakeName: parsedRequest.id, mainName: duplicateMainName, target: duplicateArchive.target!, mainSha: duplicateMainSha, published: true }
      };
    }
    if (attachment.status === 'processing' || attachment.status === 'cancelled') fail('ATTACHMENT_NOT_READY', '请先完成读取，或重试解析后再归档。');
    const text: Text = ['ready', 'needs-ocr'].includes(attachment.status) ? input.parsed(parsedRequest.id) : { parser: 'unavailable', pages: [], textRevision: '' };
    let inferred: ReturnType<typeof inferIntakeFields> = {};
    if (attachment.mediaType === 'text/markdown') {
      try { inferred = inferIntakeFields(attachment.name, original.bytes); } catch { /* Keep original metadata in the source file. */ }
    }
    let fields: IntakeFields = item.archivePlan
      ? planSchema.parse(item.archivePlan).fields
      : intakeFieldsSchema.parse({ platform: inferred.platform ?? '个人', title: inferred.title ?? attachment.name.replace(/\.(pdf|md|txt)$/iu, ''), collectedAt: inferred.collectedAt ?? date, ...inferred, ...parsedRequest.fields });
    const originalFileName = originalName(attachment);
    const body = Buffer.from(`## 原件与解析来源\n\n原文件：${JSON.stringify(attachment.name)}\n\n[查看原件](附件/${originalFileName})\n\nSHA-256：${attachment.sha256}\n\n解析器：${text.parser}；原件保真保存，以下为派生文本。${attachment.problem ? `\n\n读取提示：${attachment.problem}` : ''}\n\n${text.pages.map(page => `<!-- xiaozhao-page:${attachment.sha256}:${page.page} -->\n## 第 ${page.page} 页\n\n${page.text}\n\n`).join('')}`);
    let staged = planIntakeMain({ packageName: parsedRequest.id, mainName: '原文.md', bytes: body, fields });
    if (!item.archivePlan && exists(port, `01图书馆/来自${staged.platform}/${staged.month}/${staged.packageName}`)) {
      if (parsedRequest.fields?.title !== undefined) fail('ATTACHMENT_TITLE_CONFLICT', '归档位置已有同名资料，没有覆盖；请修改标题后重试。');
      fields = { ...fields, title: `${Array.from(fields.title).slice(0, 6).join('')} · 版本${attachment.sha256.slice(0, 8)}` };
      staged = planIntakeMain({ packageName: parsedRequest.id, mainName: '原文.md', bytes: body, fields });
      if (exists(port, `01图书馆/来自${staged.platform}/${staged.month}/${staged.packageName}`)) fail('ATTACHMENT_TITLE_CONFLICT', '该版本的归档位置已有资料，没有覆盖；请指定不同标题。');
    }
    const target = `01图书馆/来自${staged.platform}/${staged.month}/${staged.packageName}`;
    const plan = item.archivePlan
      ? planSchema.parse(item.archivePlan)
      : { fields, intakeName: parsedRequest.id, mainName: staged.mainName, target, mainSha: sha256Bytes(staged.bytes), published: false };
    if (plan.mainSha !== sha256Bytes(staged.bytes)) fail('ATTACHMENT_ARCHIVE_PLAN_CHANGED', '解析文本或归档资料已变化，请核对已有归档记录，未覆盖文件。');
    return {
      attachmentId: attachment.id, attachmentSha256: attachment.sha256, attachmentName: attachment.name,
      archiveFields: plan.fields, textRevision: text.textRevision, target: plan.target, mainName: plan.mainName,
      mainSha256: plan.mainSha, duplicate: false,
      item, attachment, original: original.bytes, originalName: originalFileName, staged, plan
    };
  }

  async function execute(request: AttachmentArchiveRequest, signal?: AbortSignal, expected?: AttachmentArchivePreview): Promise<AttachmentArchiveResult> {
    const samePlan = (preview: AttachmentArchivePreview): boolean => !expected
      || (expected.attachmentId === preview.attachmentId && expected.attachmentSha256 === preview.attachmentSha256
        && expected.mainSha256 === preview.mainSha256 && expected.target === preview.target
        && expected.mainName === preview.mainName && expected.textRevision === preview.textRevision);
    let built = await buildPreview(request, signal);
    if (!samePlan(built)) {
      fail('ATTACHMENT_ARCHIVE_PLAN_CHANGED', '附件或解析结果已变化，请重新生成预览；未写入文件。');
    }
    if (built.existing) {
      if (built.duplicateRecord && built.item.attachment.archive?.state !== 'archived') {
        built.item.attachment.archive = structuredClone(built.duplicateRecord.attachment.archive);
        built.item.attachment.duplicateOf = built.duplicateRecord.attachment.id;
        input.persist(built.item);
      }
      return built.existing;
    }
    if (!input.port) fail('ATTACHMENT_ARCHIVE_UNAVAILABLE', '当前连接不能归档附件；原件已保留。');
    // Rebuild immediately before the first durable write. This closes the gap
    // between a caller's preview and execution if parsed text changes while the
    // request is waiting in the archive queue.
    const refreshed = await buildPreview(request, signal);
    if (!samePlan(refreshed) || refreshed.attachmentSha256 !== built.attachmentSha256 || refreshed.mainSha256 !== built.mainSha256) {
      fail('ATTACHMENT_ARCHIVE_PLAN_CHANGED', '附件或解析结果已变化，请重新生成预览；未写入文件。');
    }
    const latestOriginal = input.readOriginal(refreshed.attachmentId);
    if (latestOriginal.attachment.sha256 !== refreshed.attachmentSha256 || !latestOriginal.bytes.equals(built.original)) {
      fail('ATTACHMENT_ARCHIVE_CHANGED', '附件原件发生变化，未继续归档。');
    }
    built = { ...refreshed, original: latestOriginal.bytes, attachment: latestOriginal.attachment };
    const { port, intakeService } = input.port;
    const { item, attachment, original, originalName: fileName, staged, plan } = built;
    item.archivePlan = plan;
    item.attachment.archive ??= { state: 'preparing' };
    input.persist(item);
    try {
      let operationId = item.attachment.archive.operationId;
      if (!operationId) {
        for (const name of port.listRecovery().filter(value => value.endsWith('.intent.json'))) {
          try {
            const envelope = JSON.parse(port.readRecovery(name)!.toString('utf8')) as { payload: { base?: string } };
            if (!envelope.payload.base) continue;
            const base = parseArchiveIntent(Buffer.from(envelope.payload.base));
            if (base.source === `01图书馆/小兆clipper/${plan.intakeName}` && base.target === plan.target) { operationId = base.id; break; }
          } catch { /* IntakeService independently rejects unknown recovery records. */ }
        }
      }
      let outcome;
      if (operationId) outcome = await intakeService.resume(operationId, signal);
      else {
        const source = `01图书馆/小兆clipper/${plan.intakeName}`;
        if (!port.stat(source)) {
          if (plan.published) fail('ATTACHMENT_ARCHIVE_INCOMPLETE', '已发布的资料包暂时无法定位，请核对归档记录，未重复生成。');
          signal?.throwIfAborted();
          publish(staged, plan.intakeName, fileName, original, port);
        }
        // At this point the package may already have been published. A
        // mismatch is therefore not an ordinary pre-write stale result: keep
        // it recoverable so the caller cannot present it as a clean no-write
        // conflict or silently retry a partially published package.
        if (!port.read(`${source}/${plan.mainName}`).equals(staged.bytes) || !port.read(`${source}/附件/${fileName}`).equals(original)) {
          fail('ATTACHMENT_ARCHIVE_INCOMPLETE', '暂存资料包发生变化，归档进入恢复状态；未继续归档。');
        }
        plan.published = true; item.archivePlan = plan; input.persist(item);
        // This is the execution-only boundary. Preview never calls these methods.
        const intakePreview = await intakeService.preview({ name: plan.intakeName, mainName: plan.mainName, fields: plan.fields } satisfies IntakePreviewRequest);
        signal?.throwIfAborted();
        outcome = await intakeService.commit(intakePreview.token, signal);
      }
      item.attachment.archive = { state: outcome.state === 'archived' ? 'archived' : 'needs-review', operationId: outcome.id, target: outcome.target, materialPath: `${outcome.target}/${plan.mainName}`, indexed: outcome.indexed };
      if (outcome.state === 'archived') verifyArchivedOriginal(port, item.attachment, 'ATTACHMENT_ARCHIVE_COMMITTED_ORIGINAL_CHANGED');
      input.persist(item);
      return storedResult(item.attachment, false);
    } catch (error) {
      item.attachment.archive = { ...item.attachment.archive, state: 'needs-review', problem: '本次归档尚未确认完成，原件和进度已保留；重试会先核对同一操作。' };
      input.persist(item);
      throw error;
    }
  }

  async function preview(request: AttachmentArchiveRequest, signal?: AbortSignal): Promise<AttachmentArchivePreview> {
    const built = await buildPreview(request, signal);
    const { item: _item, attachment: _attachment, original: _original, originalName: _originalName, staged: _staged, plan: _plan, duplicateRecord: _duplicateRecord, ...publicPreview } = built;
    return publicPreview;
  }

  function archive(request: AttachmentArchiveRequest, signal?: AbortSignal, expected?: AttachmentArchivePreview): Promise<AttachmentArchiveResult> {
    if (running) {
      if (running.id === request.id) return running.done;
      return Promise.reject(new PublicApiError('ATTACHMENT_ARCHIVE_BUSY', '另一份附件正在归档，请稍后重试。', 409));
    }
    const done = Promise.resolve().then(() => execute(request, signal, expected)).finally(() => { if (running?.done === done) running = undefined; });
    running = { id: request.id, done };
    return done;
  }

  return { preview, archive, close: async () => { try { await running?.done; } catch { /* Durable progress remains available for recovery. */ } } };
}
