import { createHash } from 'node:crypto';
import { constants } from 'node:fs';
import { lstat, mkdir, open, readdir, realpath, rename } from 'node:fs/promises';
import { basename, dirname, join, relative, resolve } from 'node:path';
import { PublicApiError } from '../../shared/api/errors.js';
import type { SkillDetail, SkillFolder, SkillSummary, SkillsPage } from '../../shared/api/skills.js';
import { parseFrontmatter } from '../rules/frontmatter.js';

const MAX_SKILL_BYTES = 256 * 1024; const SKILL_FILE = 'SKILL.md'; const DEFAULT_DESCRIPTION = 'No description provided.';
const RESERVED_DIRECTORY_NAMES = new Set(['env', 'scripts']); const MAX_REFERENCE_COUNT = 1_000;
export interface SkillCatalogService { list(): Promise<SkillsPage>; get(id: string): Promise<SkillDetail>; createFolder(name: string): Promise<SkillFolder>; move(skillId: string, folderId: string | null): Promise<SkillDetail>; resolveSource(skillId: string): Promise<string>; }
const err = (code: string, message: string, status = 400) => new PublicApiError(code, message, status);
const unavailable = () => err('SKILL_CATALOG_UNAVAILABLE', 'Skill catalog is unavailable.', 503);
const safeName = (name: string) => name.length > 0 && !name.startsWith('.') && name !== '.' && name !== '..' && !RESERVED_DIRECTORY_NAMES.has(name.toLowerCase()) && !/[\\/\0\u0000-\u001f\u007f]/u.test(name) && Buffer.byteLength(name) <= 255;
const digest = (v: Uint8Array) => createHash('sha256').update(v).digest('hex');
export const skillId = (name: string) => digest(Buffer.from(name, 'utf8'));
const folderId = (name: string) => digest(Buffer.from(name, 'utf8'));
const field = (v: unknown, fallback: string, max: number) => { if (typeof v !== 'string') return fallback; const x = v.replace(/\s+/gu, ' ').trim(); return x && x.length <= max && !/[\u0000-\u001f\u007f]/u.test(x) ? x : fallback; };
async function readFile(path: string): Promise<Buffer | undefined> { let h: Awaited<ReturnType<typeof open>> | undefined; try { h = await open(path, constants.O_RDONLY | constants.O_NOFOLLOW); const s = await h.stat(); if (!s.isFile() || s.size > MAX_SKILL_BYTES) return undefined; const b = Buffer.alloc(s.size); let o = 0; while (o < b.length) { const r = await h.read(b, o, b.length - o, o); if (!r.bytesRead) return undefined; o += r.bytesRead; } return b; } catch { return undefined; } finally { await h?.close().catch(() => undefined); } }
type Skill = { directoryName: string; directoryPath: string; directoryRealPath: string; bytes: Buffer; folder: SkillFolder | null };
export function createSkillCatalogService(input: { skillsRoot: string }): SkillCatalogService {
  const configuredRoot = resolve(input.skillsRoot); const parent = dirname(configuredRoot); const vault = dirname(parent);
  async function fixedRoot(): Promise<string> { try { const [v, p, r] = await Promise.all([lstat(vault), lstat(parent), lstat(configuredRoot)]); if (!v.isDirectory() || v.isSymbolicLink() || !p.isDirectory() || p.isSymbolicLink() || !r.isDirectory() || r.isSymbolicLink()) throw unavailable(); const cv = await realpath(vault); const c = await realpath(configuredRoot); if (c !== join(cv, basename(parent), basename(configuredRoot))) throw unavailable(); return c; } catch (e) { if (e instanceof PublicApiError) throw e; throw unavailable(); } }
  async function ensureRoot(): Promise<string> { try { const v = await lstat(vault); if (!v.isDirectory() || v.isSymbolicLink()) throw unavailable(); try { const p = await lstat(parent); if (!p.isDirectory() || p.isSymbolicLink()) throw unavailable(); } catch (e) { if (e instanceof PublicApiError) throw e; await mkdir(parent); } try { const r = await lstat(configuredRoot); if (!r.isDirectory() || r.isSymbolicLink()) throw unavailable(); } catch (e) { if (e instanceof PublicApiError) throw e; await mkdir(configuredRoot); } return fixedRoot(); } catch (e) { if (e instanceof PublicApiError) throw e; throw unavailable(); } }
  async function discover(root: string, name: string, folder: SkillFolder | null): Promise<Skill | undefined> { if (!safeName(name)) return; const path = join(root, name); try { const s = await lstat(path); if (!s.isDirectory() || s.isSymbolicLink()) return; const rp = await realpath(path); if (dirname(rp) !== root || basename(rp) !== name) return; const sp = join(path, SKILL_FILE); const ss = await lstat(sp); if (!ss.isFile() || ss.isSymbolicLink() || ss.size > MAX_SKILL_BYTES) return; const bytes = await readFile(sp); return bytes ? { directoryName: name, directoryPath: path, directoryRealPath: rp, bytes, folder } : undefined; } catch { return; } }
  async function layout(root: string): Promise<{ folders: SkillFolder[]; found: Skill[] }> { let names: string[]; try { names = (await readdir(root)).sort(); } catch { throw unavailable(); } const folders: SkillFolder[] = []; const found: Skill[] = []; for (const name of names) { if (!safeName(name)) continue; const direct = await discover(root, name, null); if (direct) { found.push(direct); continue; } try { const path = join(root, name); const s = await lstat(path); if (!s.isDirectory() || s.isSymbolicLink()) continue; const rp = await realpath(path); if (dirname(rp) !== root || basename(rp) !== name) continue; try { const marker = await lstat(join(path, SKILL_FILE)); if (marker) continue; } catch {} const f: SkillFolder = { id: folderId(name), name, skillCount: 0 }; for (const child of (await readdir(path)).sort()) { const x = await discover(path, child, f); if (x) found.push(x); } f.skillCount = found.filter((x) => x.folder?.id === f.id).length; folders.push(f); } catch { /* ignore unsafe entries */ } } folders.sort((a, b) => a.name.localeCompare(b.name)); found.sort((a, b) => a.directoryName.localeCompare(b.directoryName)); return { folders, found }; }
  function metadata(s: Skill): { summary: SkillSummary; markdown: string } | undefined { let data: Record<string, unknown> = {}; let body: Uint8Array = s.bytes; try { const p = parseFrontmatter(s.bytes); data = p.data; body = p.bodyBytes; } catch {} let markdown: string; try { markdown = new TextDecoder('utf-8', { fatal: true }).decode(body); } catch { return; } return { summary: { id: skillId(s.directoryName), name: field(data.name, s.directoryName, 256), description: field(data.description, DEFAULT_DESCRIPTION, 10_000), revision: digest(s.bytes), folderId: s.folder?.id ?? null, folderName: s.folder?.name ?? null }, markdown }; }
  async function refs(s: Skill): Promise<string[]> { try { const out: string[] = []; for (const n of (await readdir(s.directoryPath)).sort()) { if (!safeName(n) || n === SKILL_FILE || !n.endsWith('.md')) continue; try { const p = join(s.directoryPath, n); const st = await lstat(p); if (!st.isFile() || st.isSymbolicLink()) continue; const rp = await realpath(p); if (dirname(rp) === s.directoryRealPath && basename(rp) === n) out.push(n); } catch {} } return out.slice(0, MAX_REFERENCE_COUNT); } catch { return []; } }
  async function locate(id: string): Promise<{ root: string; skill: Skill }> { if (!/^[a-f0-9]{64}$/u.test(id)) throw err('SKILL_ID_INVALID', 'Skill id is invalid.'); const root = await fixedRoot(); const l = await layout(root); const skill = l.found.find((x) => skillId(x.directoryName) === id); if (!skill) throw err('SKILL_NOT_FOUND', 'Skill was not found.', 404); return { root, skill }; }
  async function get(id: string): Promise<SkillDetail> { const { skill } = await locate(id); const m = metadata(skill); if (!m) throw err('SKILL_NOT_FOUND', 'Skill was not found.', 404); return { ...m.summary, markdown: m.markdown, references: await refs(skill) }; }
  async function list(): Promise<SkillsPage> { const root = await fixedRoot(); const l = await layout(root); return { folders: l.folders, items: l.found.map(metadata).filter((x): x is { summary: SkillSummary; markdown: string } => !!x).map((x) => x.summary).slice(0, MAX_REFERENCE_COUNT) }; }
  async function createFolder(name: string): Promise<SkillFolder> { if (!safeName(name)) throw err('SKILL_FOLDER_INVALID', 'Skill folder is invalid.'); const root = await ensureRoot(); try { await lstat(join(root, name)); throw err('SKILL_FOLDER_CONFLICT', 'Skill folder conflicts with an existing entry.', 409); } catch (e) { if (e instanceof PublicApiError) throw e; } await mkdir(join(root, name)); return { id: folderId(name), name, skillCount: 0 }; }
  async function move(id: string, targetId: string | null): Promise<SkillDetail> { const { root, skill } = await locate(id); const l = await layout(root); const target = targetId === null ? null : l.folders.find((f) => f.id === targetId); if (targetId !== null && !/^[a-f0-9]{64}$/u.test(targetId)) throw err('SKILL_FOLDER_INVALID', 'Skill folder is invalid.'); if (targetId !== null && !target) throw err('SKILL_FOLDER_NOT_FOUND', 'Skill folder was not found.', 404); const destination = target ? join(root, target.name, skill.directoryName) : join(root, skill.directoryName); const rel = relative(root, destination); if (rel.startsWith('..') || resolve(root, rel) !== destination) throw err('SKILL_FOLDER_INVALID', 'Skill folder is invalid.'); if (destination !== skill.directoryPath) { try { await lstat(destination); throw err('SKILL_FOLDER_CONFLICT', 'Skill folder conflicts with an existing entry.', 409); } catch (e) { if (e instanceof PublicApiError) throw e; } await rename(skill.directoryPath, destination); } return get(id); }
  async function resolveSource(id: string): Promise<string> { const { skill } = await locate(id); const p = join(skill.directoryPath, SKILL_FILE); const s = await lstat(p); if (!s.isFile() || s.isSymbolicLink()) throw err('SKILL_NOT_FOUND', 'Skill was not found.', 404); return p; }
  return { list, get, createFolder, move, resolveSource };
}
