import '@testing-library/jest-dom/vitest';
import { act, cleanup, render as renderView, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { ReactElement } from 'react';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, expect, it, vi } from 'vitest';
import { IntakePage } from '../../src/client/pages/IntakePage.js';
import { type IntakeList, type IntakePreview } from '../../src/shared/api/intake.js';
const ok = <T,>(value: T) => ({ ok: true as const, value });
const render = (ui: ReactElement) => renderView(<MemoryRouter initialEntries={['/intake']}>{ui}</MemoryRouter>);
const item = { name: '测试资料包', kind: 'directory' as const, mainCandidates: ['原文.md'], fields: { platform: '个人' as const, title: '测试资料', collectedAt: '2026-09-05' } };
const data: IntakeList = { available: true, automaticArchive: false, items: [item], operations: [] };
const preview: IntakePreview = { token: 'e52917bc-a9df-482f-aae8-8c4b6da4301d', target: '01图书馆/来自个人/2026-09/测试资料', mainName: '测试资料.md', markdown: '---\n知识入库状态: 未提炼\n---\n<script>原文</script>', truncated: false, expiresAt: '2026-09-06T00:00:00.000Z' };
const api = { list: vi.fn(), preview: vi.fn(), commit: vi.fn(), resume: vi.fn() };
const trashApi = { list: vi.fn(), preview: vi.fn(), commit: vi.fn(), get: vi.fn(), restore: vi.fn(), retry: vi.fn() };
vi.mock('../../src/client/app/ConsoleRuntime.js', () => ({ useConsoleRuntime: () => ({ api: { intake: api, intakeTrash: trashApi }, refreshHealth: vi.fn() }) }));
afterEach(() => { cleanup(); localStorage.clear(); vi.resetAllMocks(); });
it('keeps every envelope inside a closed mailbox until opened and closes back to the shell', async () => {
  api.list.mockResolvedValue(ok(data)); const user = userEvent.setup(); render(<IntakePage />);
  const mailbox = await screen.findByRole('button', { name: '打开收件箱' });
  expect(mailbox).toHaveAttribute('aria-expanded', 'false');
  expect(screen.queryByRole('button', { name: '整理 测试资料包' })).not.toBeInTheDocument();
  expect(screen.queryByLabelText('原始标题')).not.toBeInTheDocument();
  await user.click(mailbox);
  expect(screen.getByRole('button', { name: '整理 测试资料包' })).toBeVisible();
  expect(screen.queryByLabelText('原始标题')).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '合上收件箱' }));
  expect(screen.queryByRole('button', { name: '整理 测试资料包' })).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: '打开收件箱' })).toHaveFocus();
  expect(api.preview).not.toHaveBeenCalled(); expect(api.commit).not.toHaveBeenCalled();
});
it('keeps edited envelope fields when returning to the mailbox and reopening the same envelope', async () => {
  api.list.mockResolvedValue(ok(data)); const user = userEvent.setup(); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  await user.clear(screen.getByLabelText('原始标题'));
  await user.type(screen.getByLabelText('原始标题'), '尚未归档的修改');
  await user.click(screen.getByRole('button', { name: '合上收件箱' }));
  expect(screen.queryByLabelText('原始标题')).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '打开收件箱' }));
  expect(screen.queryByLabelText('原始标题')).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  expect(screen.getByLabelText('原始标题')).toHaveValue('尚未归档的修改');
  expect(api.preview).not.toHaveBeenCalled(); expect(api.commit).not.toHaveBeenCalled();
});
it('states that unarchived edits only live on the current page before the user leaves the form', async () => {
  api.list.mockResolvedValue(ok(data)); const user = userEvent.setup(); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  expect(screen.getByText(/尚未归档的整理内容只保留在当前页面/u)).toBeVisible();
  expect(screen.getByText(/离开前请先预览并确认归档/u)).toBeVisible();
});
it('can discard a file without metadata without opening or archiving its envelope', async () => {
  api.list.mockResolvedValue(ok({ ...data, items: [{ name: '录音.mp3', kind: 'file', mainCandidates: [], fields: {} }] }));
  trashApi.preview.mockResolvedValue(ok({ id: preview.token, name: '录音.mp3', title: '录音.mp3', kind: 'file', bytes: 12, fileCount: 1, expiresAt: '2099-01-01T00:00:00.000Z' }));
  const user = userEvent.setup(); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(await screen.findByRole('button', { name: '移入回收站：录音.mp3' }));
  expect(await screen.findByRole('button', { name: '确认移入回收站' })).toBeEnabled();
  expect(screen.getByRole('button', { name: '合上收件箱' })).toBeDisabled();
  expect(screen.queryByRole('region', { name: '归档预览' })).not.toBeInTheDocument();
  expect(api.preview).not.toHaveBeenCalled(); expect(api.commit).not.toHaveBeenCalled();
  await user.click(screen.getByRole('button', { name: '取消' }));
  expect(trashApi.commit).not.toHaveBeenCalled();
  expect(screen.getByRole('button', { name: '移入回收站：录音.mp3' })).toHaveFocus();
});
it('only unfolds the archive sheet after opening an envelope and removes it on close', async () => {
  api.list.mockResolvedValue(ok(data)); const user = userEvent.setup(); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  const envelope = await screen.findByRole('button', { name: '整理 测试资料包' });
  expect(screen.queryByRole('region', { name: '归档整理单' })).not.toBeInTheDocument();
  expect(screen.queryByLabelText('原始标题')).not.toBeInTheDocument();
  await user.click(envelope);
  expect(envelope).toHaveAttribute('aria-pressed', 'true');
  expect(screen.getByRole('region', { name: '归档预览' })).toBeVisible();
  await user.click(screen.getByRole('button', { name: '关闭归档预览' }));
  expect(screen.queryByRole('region', { name: '归档预览' })).not.toBeInTheDocument();
  expect(screen.queryByRole('region', { name: '归档整理单' })).not.toBeInTheDocument();
  expect(envelope).toHaveAttribute('aria-pressed', 'false');
  expect(envelope).toHaveFocus();
});
it('shows an honest empty state and explains detection versus archive', async () => {
  api.list.mockResolvedValue(ok({ ...data, items: [] })); const user = userEvent.setup(); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  expect(await screen.findByText('收件箱是空的')).toBeVisible();
  expect(screen.getByText(/浏览器剪辑插件保存的收藏/u)).toBeVisible();
  expect(screen.getByText(/自动识别.*确认后归档/u)).toBeVisible(); expect(api.commit).not.toHaveBeenCalled();
});
it('previews literal content, then commits only after explicit confirmation', async () => {
  const user = userEvent.setup(); api.list.mockResolvedValue(ok(data)); api.preview.mockResolvedValue(ok(preview));
  api.commit.mockResolvedValue(ok({ id: preview.token, target: preview.target, state: 'archived', indexed: true })); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(await screen.findByRole('button', { name: '整理 测试资料包' }));
  await user.click(screen.getByRole('button', { name: '预览归档结果' }));
  expect(await screen.findByText(/<script>原文<\/script>/u)).toBeVisible(); expect(document.querySelector('script')).toBeNull();
  expect(api.commit).not.toHaveBeenCalled();
  await user.click(screen.getByRole('button', { name: '确认归档' }));
  await waitFor(() => expect(api.commit).toHaveBeenCalledWith(preview.token));
  expect(await screen.findByText(/归档完成，已更新资料列表/u)).toBeVisible();
  expect(screen.getByRole('link', { name: '提炼这份' })).toHaveAttribute('href', `/extractions/new?materialPath=${encodeURIComponent(`${preview.target}/${preview.mainName}`)}`);
  await user.click(screen.getByRole('button', { name: '继续整理' }));
  expect(screen.queryByRole('link', { name: '提炼这份' })).not.toBeInTheDocument();
  expect(screen.getByRole('button', { name: '整理 测试资料包' })).toBeVisible();
});
it('invalidates a preview if the user changes fields', async () => {
  const user = userEvent.setup(); api.list.mockResolvedValue(ok(data)); api.preview.mockResolvedValue(ok(preview)); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(await screen.findByRole('button', { name: '整理 测试资料包' })); await user.click(screen.getByRole('button', { name: '预览归档结果' }));
  await screen.findByRole('button', { name: '确认归档' }); await user.type(screen.getByLabelText('原始标题'), '修改');
  expect(screen.queryByRole('button', { name: '确认归档' })).not.toBeInTheDocument();
});
it('shows a pending operation with an explicit resume action', async () => {
  api.list.mockResolvedValue(ok({ ...data, items: [], operations: [{ id: preview.token, target: preview.target, state: 'pending' }] })); render(<IntakePage />);
  expect(await screen.findByRole('button', { name: '继续核验归档' })).toBeVisible();
  expect(api.resume).not.toHaveBeenCalled();
});
it('makes preserved existing author and source link read-only rather than silently ignoring edits', async () => {
  const user = userEvent.setup(); api.list.mockResolvedValue(ok({ ...data, items: [{ ...item, fields: { ...item.fields, author: '原作者', url: 'https://example.com/original' } }] })); render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(await screen.findByRole('button', { name: '整理 测试资料包' }));
  expect(screen.getByLabelText('作者（可留空）')).toHaveAttribute('readonly');
  expect(screen.getByLabelText('原始链接（可留空）')).toHaveAttribute('readonly');
});
it('does not close or submit twice while the preview is being checked', async () => {
  const user = userEvent.setup(); api.list.mockResolvedValue(ok(data));
  let finish!: (value: ReturnType<typeof ok<IntakePreview>>) => void;
  api.preview.mockImplementation(() => new Promise(resolve => { finish = resolve; }));
  render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(await screen.findByRole('button', { name: '整理 测试资料包' }));
  await user.click(screen.getByRole('button', { name: '预览归档结果' }));
  expect(screen.getByRole('button', { name: '关闭归档预览' })).toBeDisabled();
  expect(screen.getByRole('button', { name: '合上收件箱' })).toBeDisabled();
  await user.click(screen.getByRole('button', { name: '合上收件箱' }));
  await user.keyboard('{Escape}');
  expect(screen.getByRole('heading', { name: '整理这份资料' })).toBeInTheDocument();
  expect(screen.getByRole('button', { name: '正在核验…' })).toBeDisabled();
  await act(async () => finish(ok(preview)));
  expect(await screen.findByRole('button', { name: '确认归档' })).toBeEnabled();
  expect(api.preview).toHaveBeenCalledTimes(1); expect(api.commit).not.toHaveBeenCalled();
});
it('recovers a rejected first load without confusing it with an empty inbox', async () => {
  const user = userEvent.setup(); api.list.mockRejectedValueOnce(new Error('offline')).mockResolvedValue(ok(data));
  render(<IntakePage />);
  expect(await screen.findByRole('alert')).toHaveTextContent('本地连接中断');
  expect(screen.queryByText('收件箱是空的')).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '刷新收件箱' }));
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  expect(await screen.findByRole('button', { name: '整理 测试资料包' })).toBeVisible();
  expect(screen.queryByRole('alert')).not.toBeInTheDocument();
});
it('keeps the mailbox and edited fields in place during a commit and after a failed response', async () => {
  const user = userEvent.setup(); api.list.mockResolvedValue(ok(data)); api.preview.mockResolvedValue(ok(preview));
  let fail!: (error: Error) => void;
  api.commit.mockImplementation(() => new Promise((_resolve, reject) => { fail = reject; }));
  render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  await user.type(screen.getByLabelText('原始标题'), '（已核对）');
  await user.click(screen.getByRole('button', { name: '预览归档结果' }));
  await user.click(await screen.findByRole('button', { name: '确认归档' }));
  expect(screen.getByRole('button', { name: '合上收件箱' })).toBeDisabled();
  expect(screen.getByLabelText('原始标题')).toBeDisabled();
  await user.keyboard('{Escape}');
  expect(screen.getByLabelText('原始标题')).toHaveValue('测试资料（已核对）');
  await act(async () => fail(new Error('connection lost')));
  expect(await screen.findByRole('alert')).toHaveTextContent('本地连接中断');
  await user.click(screen.getByRole('button', { name: '合上收件箱' }));
  await user.click(screen.getByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  expect(screen.getByLabelText('原始标题')).toHaveValue('测试资料（已核对）');
  expect(api.commit).toHaveBeenCalledOnce();
});
it('preserves an edited envelope while separately resuming an older archive', async () => {
  const user = userEvent.setup();
  api.list.mockResolvedValue(ok({ ...data, operations: [{ id: preview.token, target: preview.target, state: 'pending' }] }));
  api.resume.mockResolvedValue(ok({ id: preview.token, target: preview.target, state: 'archived', indexed: true }));
  render(<IntakePage />);
  await user.click(await screen.findByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  await user.clear(screen.getByLabelText('原始标题'));
  await user.type(screen.getByLabelText('原始标题'), '仍在整理的资料');
  await user.click(screen.getByRole('button', { name: '继续核验归档' }));
  await screen.findByText(/归档完成，已更新资料列表/u);
  expect(screen.queryByRole('link', { name: '提炼这份' })).not.toBeInTheDocument();
  expect(screen.getByRole('link', { name: '查看已归档资料' })).toHaveAttribute('href', `/library?${new URLSearchParams({ mode: 'source', folder: preview.target.slice('01图书馆/'.length) })}`);
  await user.click(screen.getByRole('button', { name: '合上收件箱' }));
  await user.click(screen.getByRole('button', { name: '打开收件箱' }));
  await user.click(screen.getByRole('button', { name: '整理 测试资料包' }));
  expect(screen.getByLabelText('原始标题')).toHaveValue('仍在整理的资料');
  expect(api.resume).toHaveBeenCalledOnce(); expect(api.commit).not.toHaveBeenCalled();
});
