// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import { act, cleanup, render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, expect, it, vi } from 'vitest';
import type { ApiClientResult, ReadConsoleApi } from '../../src/client/api/client.js';
import type { SkillFolderTrashEntry } from '../../src/shared/api/skills.js';
import { SkillsPage } from '../../src/client/pages/SkillsPage.js';
const runtime: { api: Pick<ReadConsoleApi, 'skills'> } = { api: {} };
vi.mock('../../src/client/app/ConsoleRuntime.js', () => ({ useConsoleRuntime: () => runtime }));
afterEach(() => { cleanup(); vi.useRealTimers(); });
const ok = <T,>(value: T): ApiClientResult<T> => ({ ok: true, value });
const bad = (message: string): ApiClientResult<SkillFolderTrashEntry> => ({ ok: false, state: { status: 'operation-error', message } });
function setup() {
  const folders = ['写作', '拍摄', '保留'].map((name, index) => ({ id: String(index + 1).repeat(64), name, skillCount: index }));
  let active = [...folders];
  let trash: SkillFolderTrashEntry[] = [];
  const previewFolderTrash = vi.fn(async (id: string) => { const folder = folders.find(value => value.id === id)!; return ok({ ...folder, folderId: id, id: `00000000-0000-4000-8000-${String(folders.indexOf(folder)).padStart(12, '0')}`, entryCount: folder.skillCount + 1, expiresAt: new Date(Date.now() + 300_000).toISOString() }); });
  const trashFolder = vi.fn(async (id: string): Promise<ApiClientResult<SkillFolderTrashEntry>> => { const folder = folders[Number(id.slice(-12))]!; active = active.filter(value => value.id !== folder.id); const entry = { ...folder, folderId: folder.id, id, status: 'trashed' as const, createdAt: new Date().toISOString() }; trash.push(entry); return ok(entry); });
  const restoreFolder = vi.fn(async (id: string): Promise<ApiClientResult<SkillFolderTrashEntry>> => { const entry = trash.find(value => value.id === id)!; trash = trash.filter(value => value.id !== id); active.push(folders.find(value => value.id === entry.folderId)!); return ok({ ...entry, status: 'restored' }); });
  const list = vi.fn(async () => ok({ folders: active, items: [] }));
  runtime.api = { skills: { list, get: vi.fn(), createFolder: vi.fn(), move: vi.fn(), previewFolderTrash, trashFolder, restoreFolder, listFolderTrash: vi.fn(async () => ok({ items: trash })) } };
  return { folders, previewFolderTrash, trashFolder, restoreFolder, list };
}
it('selects folders independently of navigation, toggles all, previews exact selection and cancels without writes', async () => {
  const f = setup(); const user = userEvent.setup(); render(<SkillsPage />);
  await user.click(await screen.findByRole('checkbox', { name: '选择文件夹：写作' }));
  expect(screen.getByRole('button', { name: '未分类 0' })).toHaveAttribute('aria-pressed', 'true');
  expect(screen.queryByRole('checkbox', { name: /未分类/ })).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '全选文件夹' }));
  expect(screen.getByText('已选 3 个文件夹')).toBeVisible();
  await user.click(screen.getByRole('button', { name: '取消全选文件夹' }));
  expect(screen.getByText('已选 0 个文件夹')).toBeVisible();
  await user.click(screen.getByRole('button', { name: '写作 0' }));
  await user.click(screen.getByRole('checkbox', { name: '选择文件夹：写作' }));
  await user.click(screen.getByRole('checkbox', { name: '选择文件夹：拍摄' }));
  expect(screen.queryByRole('button', { name: '移到回收站' })).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '批量移到回收站（2）' }));
  const dialog = await screen.findByRole('dialog', { name: '回收选中的 2 个文件夹？' });
  expect(dialog).toHaveTextContent('写作'); expect(dialog).toHaveTextContent('拍摄'); expect(dialog).not.toHaveTextContent('保留');
  expect(dialog).toHaveTextContent('隐藏文件'); expect(f.previewFolderTrash).toHaveBeenCalledTimes(2);
  await user.click(within(dialog).getByRole('button', { name: '取消回收' }));
  expect(f.trashFolder).not.toHaveBeenCalled(); expect(screen.getByText('已选 2 个文件夹')).toBeVisible();
});
it('retains only failed selections and undoes successful items as a batch without double submission', async () => {
  const f = setup(); const user = userEvent.setup(); render(<SkillsPage />);
  await user.click(await screen.findByRole('button', { name: '全选文件夹' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（3）' }));
  f.trashFolder.mockResolvedValueOnce(bad('目录变化，请重新预览。'));
  await user.dblClick(await screen.findByRole('button', { name: '确认回收这 3 个文件夹' }));
  expect(await screen.findByText('已回收 2 个文件夹，1 个未完成。')).toBeVisible();
  expect(f.trashFolder).toHaveBeenCalledTimes(3);
  expect(await screen.findByRole('checkbox', { name: '选择文件夹：写作' })).toBeChecked();
  expect(screen.getByRole('alert')).toHaveTextContent('写作：目录变化');
  await user.click(screen.getByRole('button', { name: '撤销本批回收' }));
  expect(await screen.findByText('已恢复 2 个文件夹。')).toBeVisible();
  expect(f.restoreFolder).toHaveBeenCalledTimes(2);
  expect(await screen.findByRole('checkbox', { name: '选择文件夹：拍摄' })).not.toBeChecked();
  expect(screen.getByRole('checkbox', { name: '选择文件夹：写作' })).toBeChecked();
});
it('restores multiple recycled folders and retains conflicting items for retry', async () => {
  const f = setup(); const user = userEvent.setup(); render(<SkillsPage />);
  await user.click(await screen.findByRole('button', { name: '全选文件夹' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（3）' }));
  await user.click(await screen.findByRole('button', { name: '确认回收这 3 个文件夹' }));
  await screen.findByText('已回收 3 个文件夹。');
  await user.click(screen.getByRole('button', { name: '文件夹回收站' }));
  await user.click(await screen.findByRole('button', { name: '全选可恢复文件夹' }));
  f.restoreFolder.mockResolvedValueOnce(bad('原位置已有同名文件夹。'));
  await user.click(screen.getByRole('button', { name: '批量恢复（3）' }));
  expect(await screen.findByText('已恢复 2 个文件夹，1 个未完成。')).toBeVisible();
  expect(await screen.findByRole('checkbox', { name: '选择回收文件夹：写作' })).toBeChecked();
  await user.click(screen.getByRole('button', { name: '批量恢复（1）' }));
  expect(await screen.findByText('已恢复 1 个文件夹。')).toBeVisible();
});
it('blocks expiry before confirmation and lets the user explicitly refresh the preview', async () => {
  const f = setup(); const user = userEvent.setup();
  f.previewFolderTrash.mockImplementation(async id => ok({ ...f.folders[0]!, folderId: id, id: '00000000-0000-4000-8000-000000000000', entryCount: 0, expiresAt: new Date(Date.now() - 10).toISOString() }));
  render(<SkillsPage />);
  await user.click(await screen.findByRole('checkbox', { name: '选择文件夹：写作' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（1）' }));
  expect(await screen.findByRole('button', { name: '确认回收这 1 个文件夹' })).toBeDisabled();
  expect(screen.getByText('回收预览已过期，请重新预览后再确认。')).toBeVisible();
  await user.click(screen.getByRole('button', { name: '重新预览所选文件夹' }));
  expect(f.previewFolderTrash).toHaveBeenCalledTimes(2); expect(f.trashFolder).not.toHaveBeenCalled();
});
it('locks related controls while mutating and stops scheduling after unmount', async () => {
  const f = setup(); const user = userEvent.setup(); let finish!: (value: ApiClientResult<SkillFolderTrashEntry>) => void;
  f.trashFolder.mockImplementationOnce(() => new Promise(resolve => { finish = resolve; }));
  const view = render(<SkillsPage />);
  await user.click(await screen.findByRole('button', { name: '全选文件夹' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（3）' }));
  await user.click(await screen.findByRole('button', { name: '确认回收这 3 个文件夹' }));
  expect(screen.getByRole('button', { name: '未分类 0' })).toBeDisabled();
  expect(screen.getByRole('button', { name: '新建文件夹' })).toBeDisabled();
  expect(screen.getByRole('checkbox', { name: '选择文件夹：拍摄' })).toBeDisabled();
  view.unmount();
  await act(async () => finish(ok({ id: '00000000-0000-4000-8000-000000000000', folderId: f.folders[0]!.id, name: '写作', skillCount: 0, createdAt: new Date().toISOString(), status: 'trashed' })));
  expect(f.trashFolder).toHaveBeenCalledTimes(1);
});
it('keeps the whole selection when one preview fails and does not offer an incomplete confirmation', async () => {
  const f = setup(); const user = userEvent.setup();
  f.previewFolderTrash.mockRejectedValueOnce(new Error('network')); render(<SkillsPage />);
  await user.click(await screen.findByRole('button', { name: '全选文件夹' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（3）' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('写作：无法预览');
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument();
  expect(screen.getByText('已选 3 个文件夹')).toBeVisible(); expect(f.trashFolder).not.toHaveBeenCalled();
  await user.click(screen.getByRole('button', { name: '刷新 Skill 库' }));
  expect(await screen.findByText('已选 0 个文件夹')).toBeVisible();
});
it('does not report an unacknowledged move as success and still exposes its persistent recycle entry', async () => {
  const f = setup(); const user = userEvent.setup(); const original = f.trashFolder.getMockImplementation()!;
  f.trashFolder.mockImplementationOnce(async id => { await original(id); throw new Error('response lost after server commit'); });
  render(<SkillsPage />);
  await user.click(await screen.findByRole('checkbox', { name: '选择文件夹：写作' }));
  await user.click(screen.getByRole('button', { name: '批量移到回收站（1）' }));
  await user.click(await screen.findByRole('button', { name: '确认回收这 1 个文件夹' }));
  expect(await screen.findByText('已回收 0 个文件夹，1 个未完成。')).toBeVisible();
  expect(screen.getByRole('alert')).toHaveTextContent('结果未确认');
  expect(screen.queryByRole('button', { name: '撤销本批回收' })).not.toBeInTheDocument();
  await user.click(screen.getByRole('button', { name: '文件夹回收站' }));
  expect(await screen.findByRole('checkbox', { name: '选择回收文件夹：写作' })).toBeVisible();
});
